version: '3.4'

networks:
  default:
    driver:
      bridge
  front:
    driver:
      bridge

services:

  # This is a "virtual service" used to provide a base image
  dind-java-base-image:
    build: ./dind-java-base-image
    image: dind-java-base-image # Fix name to avoid inheritance
    read_only: true # Less space used
    entrypoint: "true" # Start and stop just to justify the service existence

  front:
    build: ./front/
    image: front
    restart: unless-stopped
    read_only: true
    ports:
    - "${EXTERNAL_PORT}:${EXTERNAL_PORT}"
    depends_on:
    - jenkins
    - gitserver
    - devbox
    networks:
    - default
    - front
    volumes:
    - nginx-tmp:/tmp
    - nginx-cache:/var/cache/nginx
    - nginx-run:/var/run
    extra_hosts:
    - "${EXTERNAL_DOMAIN}:${DOCKER_BRIDGE_IP}"
    environment:
    - EXTERNAL_DOMAIN=${EXTERNAL_DOMAIN}
    - EXTERNAL_PORT=${EXTERNAL_PORT}
    - REGISTRY_URL=${REGISTRY_URL}
    - REGISTRY_USER=${COMPOSE_PROJECT_NAME:-registry_user}

  gitserver:
    build:
      context: ./gitserver/
      args:
      - first_user=butler
      - source_repo_to_mirror=https://github.com/oufti-playground/demoapp|demoapp
    image: gitserver
    restart: unless-stopped
    extra_hosts:
    - "${EXTERNAL_DOMAIN}:${DOCKER_BRIDGE_IP}"
    environment:
    - EXTERNAL_DOMAIN=${EXTERNAL_DOMAIN}
    - EXTERNAL_URL=http://${EXTERNAL_DOMAIN}:${EXTERNAL_PORT}/gitserver

  jenkins:
    build: ./jenkins/
    image: jenkins
    read_only: true
    restart: unless-stopped
    volumes:
    - jenkins-data:/var/jenkins_home
    - /tmp
    - jenkins-war:/var/jenkins_home/war
    - jenkins-plugins:/var/jenkins_home/plugins
    extra_hosts:
    - "${EXTERNAL_DOMAIN}:${DOCKER_BRIDGE_IP}"
    environment:
    - JENKINS_EXTERNAL_URL=http://${EXTERNAL_DOMAIN}:${EXTERNAL_PORT}/jenkins
    - JENKINS_OPTS=--prefix=/jenkins

  jenkins-docker-node:
    depends_on:
    - dind-java-base-image
    build: ./jenkins-dind-java-node/
    image: jenkins-docker-node
    restart: unless-stopped
    privileged: true
    volumes:
    - jenkins-docker-node-data:/home/jenkins
    - /var/run
    - /etc
    - /tmp
    extra_hosts:
    - "${EXTERNAL_DOMAIN}:${DOCKER_BRIDGE_IP}"
    environment:
    - JENKINS_SLAVE_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ== vagrant insecure public key

  jenkins-maven-jdk8-node:
    depends_on:
    - dind-java-base-image
    build: ./jenkins-dind-java-node/
    image: jenkins-maven-jdk8-node
    restart: unless-stopped
    read_only: true
    volumes:
    - jenkins-maven-jdk8-node-data:/home/jenkins
    - /etc
    - /tmp
    extra_hosts:
    - "${EXTERNAL_DOMAIN}:${DOCKER_BRIDGE_IP}"
    environment:
    - START_DOCKER=no
    - JENKINS_SLAVE_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ== vagrant insecure public key

  jenkins-maven-jdk7-node:
    depends_on:
    - jenkins-maven-jdk8-node
    build: ./jenkins-jdk7-node/
    image: jenkins-maven-jdk7-node
    restart: unless-stopped
    read_only: true
    volumes:
    - jenkins-maven-jdk7-node-data:/home/jenkins
    - /etc
    - /tmp
    extra_hosts:
    - "${EXTERNAL_DOMAIN}:${DOCKER_BRIDGE_IP}"
    environment:
    - START_DOCKER=no
    - JENKINS_SLAVE_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ== vagrant insecure public key

  devbox:
    depends_on:
    - jenkins-maven-jdk8-node
    build: ./devbox/
    image: devbox
    restart: unless-stopped
    read_only: true
    privileged: true
    volumes:
    - devbox-tmp:/tmp
    extra_hosts:
    - "${EXTERNAL_DOMAIN}:${DOCKER_BRIDGE_IP}"

  docker-service:
    image: verb/socat:alpine
    restart: unless-stopped
    read_only: true
    command: tcp-listen:2375,reuseaddr,fork unix:/docker.sock
    volumes:
    - /var/run/docker.sock:/docker.sock

  docker-registry:
    image: registry:2
    restart: unless-stopped
    read_only: true

# TMPFS Volumes from https://docs.docker.com/engine/reference/commandline/volume_create/#driver-specific-options
volumes:
  nginx-tmp:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: rw,noexec,size=10m
  nginx-cache:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: rw,noexec,size=10m
  nginx-run:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: rw,noexec,size=100k
  jenkins-data:
    driver: local
  jenkins-war:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: rw,noexec,size=100m
  jenkins-plugins:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: rw,noexec,size=400m
  devbox-tmp:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: rw,noexec,size=10m
  jenkins-docker-node-data:
    driver: local
  jenkins-maven-jdk8-node-data:
    driver: local
  jenkins-maven-jdk7-node-data:
    driver: local
