version: '3.4'

networks:
  default:
    driver:
      bridge
  front:
    driver:
      bridge

services:
  front:
    build: ./front/
    image: ${DOCKER_USERNAME}/oufti-front
    restart: unless-stopped
    read_only: true
    ports:
      - "${EXTERNAL_PORT}:${EXTERNAL_PORT}"
    depends_on:
      - jenkins
      - gitserver
      - devbox
    networks:
      - default
      - front
    extra_hosts:
      - "${EXTERNAL_DOMAIN}:${DOCKER_BRIDGE_IP}"
    environment:
      - EXTERNAL_DOMAIN=${EXTERNAL_DOMAIN}
      - EXTERNAL_PORT=${EXTERNAL_PORT}
      - REGISTRY_URL=${REGISTRY_URL}
      - REGISTRY_USER=${COMPOSE_PROJECT_NAME:-registry_user}

  gitserver:
    build:
      context: ./gitserver/
    image: ${DOCKER_USERNAME}/oufti-gitserver
    restart: unless-stopped
    extra_hosts:
      - "${EXTERNAL_DOMAIN}:${DOCKER_BRIDGE_IP}"
    environment:
      - EXTERNAL_URL=http://${EXTERNAL_DOMAIN}:${EXTERNAL_PORT}/gitserver
      - EXTERNAL_DOMAIN=${EXTERNAL_DOMAIN}
      - FIRST_USER=butler
      - LOAD_SSH_KEY_FROM_JENKINS=true # Autoload the BlueOcean SSH Key into Gitea
      - SOURCE_REPO_CONFIG=/tmp/repositories.json
    volumes:
      - /app/data
      - ./gitserver/repositories.json:/tmp/repositories.json:ro
    healthcheck:
      test: ["CMD", "wget", "http://butler:butler@localhost:3000/butler/demoapp","--spider"]
      interval: 10s
      timeout: 2s
      retries: 3
      start_period: 10s

  gitserver-db:
    image: postgres:10-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_DB=gitea
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost","5432"]
      interval: 10s
      timeout: 2s
      retries: 3
      start_period: 10s

  jenkins:
    build: ./jenkins/
    image: ${DOCKER_USERNAME}/oufti-jenkins
    read_only: true
    restart: unless-stopped
    volumes:
      - /var/jenkins_home
      - /tmp
    extra_hosts:
      - "${EXTERNAL_DOMAIN}:${DOCKER_BRIDGE_IP}"
    environment:
      - JENKINS_EXTERNAL_URL=http://${EXTERNAL_DOMAIN}:${EXTERNAL_PORT}/jenkins
      - JENKINS_OPTS=--prefix=/jenkins

  jenkins-production-node:
    build:
      context: ./dind-java-images/
      target: jenkins-maven-jdk8-node
    image: ${DOCKER_USERNAME}/oufti-jenkins-production-node
    restart: unless-stopped
    privileged: true
    extra_hosts:
      - "${EXTERNAL_DOMAIN}:${DOCKER_BRIDGE_IP}"
    environment:
      - JENKINS_SLAVE_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ== vagrant insecure public key

  jenkins-maven-jdk8-node:
    build:
      context: ./dind-java-images/
      target: jenkins-maven-jdk8-node
    image: ${DOCKER_USERNAME}/oufti-jenkins-maven-jdk8-node
    restart: unless-stopped
    privileged: true
    extra_hosts:
      - "${EXTERNAL_DOMAIN}:${DOCKER_BRIDGE_IP}"
    environment:
      - JENKINS_SLAVE_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ== vagrant insecure public key

  jenkins-maven-jdk9-node:
    build: ./jenkins-maven-jdk9-node/
    image: ${DOCKER_USERNAME}/oufti-jenkins-maven-jdk9-node
    restart: unless-stopped
    read_only: true
    extra_hosts:
      - "${EXTERNAL_DOMAIN}:${DOCKER_BRIDGE_IP}"
    environment:
      - START_DOCKER=no
      - JENKINS_SLAVE_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ== vagrant insecure public key

  devbox:
    build:
      context: ./dind-java-images/
      target: devbox
    image: ${DOCKER_USERNAME}/oufti-devbox
    restart: unless-stopped
    read_only: true
    privileged: true
    extra_hosts:
      - "${EXTERNAL_DOMAIN}:${DOCKER_BRIDGE_IP}"

  docker-service:
    build: ./docker-service/
    image: ${DOCKER_USERNAME}/oufti-docker-service
    restart: unless-stopped
    read_only: true
    command: tcp-listen:2375,reuseaddr,fork unix:/docker.sock
    volumes:
      - /var/run/docker.sock:/docker.sock
